parameters:
  - name: VersionNumber
    type: string
    default: '1.0.0'
  - name: JavaVersion
    type: string
    default: '21'
  - name: goal
    type: string
    default: 'install'

trigger:
  branches:
    include:
      - '*' #Build all branches.You typically don't want to change this
    exclude:
      - 'main'

pool:
  vmImage: 'windows-latest'

#Don't change this
resources:
  repositories:
    - repository: devops
      type: git
      name: devops
      ref: master

jobs:
  - template: templates/maven/jobs.yml@devops
    parameters:
      poms: ['qa-automation-nimbus/pom.xml','qa-automation-nimbus/NIMBISSharedClasses/pom.xml']
      JavaVersion: ${{ parameters.JavaVersion }}
      goal: ${{ parameters.goal }}
      #publishPatterns: ['settings.xml']
      publishPath: 'qa-automation-nimbus'
      #additionalPublishPaths: ['qa-automation-nimbus/pom.xml','qa-automation-nimbus/NIMBISSharedClasses/pom.xml']